
vector_inventory2 <- 
  tabPanel("Vector Inventory 2 - Cassette", value = "vector_inventory_2", hr(),
    div(id = "vector_inventory_2_form",
      panel_div(class_type = "default",
                content = tags$div(
                  fluidRow(
                    column(12,
                           column(2, h4("Cassette 1"),
                                  selectInput("vector_inventory_2_Cassette1Promoter","Promoter", choices = NULL),
                                  selectInput("vector_inventory_2_Cassette1Gene","Gene", choices =  NULL),
                                  selectInput("vector_inventory_2_Cassette1Teminator","Teminator", choices = NULL),
                                  selectInput("vector_inventory_2_Cassette1Feature1","Add Feature", choices = NULL),
                                  textInput("vector_inventory_2_Cassette1Feature1Desc",""),
                                  selectInput("vector_inventory_2_Cassette1Feature2","Add Feature", choices = NULL),
                                  textInput("vector_inventory_2_Cassette1Feature2Desc",""),
                                  selectInput("vector_inventory_2_Cassette1Feature3","Add Feature", choices = NULL),
                                  textInput("vector_inventory_2_Cassette1Feature3Desc",""),
                                  
                                  br(), hr(),
                                  h4("Cassette 6"),
                                  selectInput("vector_inventory_2_Cassette6Promoter","Promoter", choices = NULL),
                                  selectInput("vector_inventory_2_Cassette6Gene","Gene", choices =  NULL),
                                  selectInput("vector_inventory_2_Cassette6Teminator","Teminator", choices = NULL),
                                  selectInput("vector_inventory_2_Cassette6Feature1","Add Feature", choices = NULL),
                                  textInput("vector_inventory_2_Cassette6Feature1Desc",""),
                                  selectInput("vector_inventory_2_Cassette6Feature2","Add Feature", choices = NULL),
                                  textInput("vector_inventory_2_Cassette6Feature2Desc",""),
                                  selectInput("vector_inventory_2_Cassette6Feature3","Add Feature", choices = NULL),
                                  textInput("vector_inventory_2_Cassette6Feature3Desc","")
                                  
                                  ),
                           column(2, h4("Cassette 2"),
                                  selectInput("vector_inventory_2_Cassette2Promoter","Promoter", choices = NULL),
                                  selectInput("vector_inventory_2_Cassette2Gene","Gene", choices =  NULL),
                                  selectInput("vector_inventory_2_Cassette2Teminator","Teminator", choices = NULL),
                                  selectInput("vector_inventory_2_Cassette2Feature1","Add Feature", choices = NULL),
                                  textInput("vector_inventory_2_Cassette2Feature1Desc",""),
                                  selectInput("vector_inventory_2_Cassette2Feature2","Add Feature", choices = NULL),
                                  textInput("vector_inventory_2_Cassette2Feature2Desc",""),
                                  selectInput("vector_inventory_2_Cassette2Feature3","Add Feature", choices = NULL),
                                  textInput("vector_inventory_2_Cassette2Feature3Desc",""),
                                  
                                  br(), hr(),
                                  h4("Cassette 7"),
                                  selectInput("vector_inventory_2_Cassette7Promoter","Promoter", choices = NULL),
                                  selectInput("vector_inventory_2_Cassette7Gene","Gene", choices =  NULL),
                                  selectInput("vector_inventory_2_Cassette7Teminator","Teminator", choices = NULL),
                                  selectInput("vector_inventory_2_Cassette7Feature1","Add Feature", choices = NULL),
                                  textInput("vector_inventory_2_Cassette7Feature1Desc",""),
                                  selectInput("vector_inventory_2_Cassette7Feature2","Add Feature", choices = NULL),
                                  textInput("vector_inventory_2_Cassette7Feature2Desc",""),
                                  selectInput("vector_inventory_2_Cassette7Feature3","Add Feature", choices = NULL),
                                  textInput("vector_inventory_2_Cassette7Feature3Desc",""),
                           ),
                           column(2, h4("Cassette 3"),
                                  selectInput("vector_inventory_2_Cassette3Promoter","Promoter", choices = NULL),
                                  selectInput("vector_inventory_2_Cassette3Gene","Gene", choices =  NULL),
                                  selectInput("vector_inventory_2_Cassette3Teminator","Teminator", choices = NULL),
                                  selectInput("vector_inventory_2_Cassette3Feature1","Add Feature", choices = NULL),
                                  textInput("vector_inventory_2_Cassette3Feature1Desc",""),
                                  selectInput("vector_inventory_2_Cassette3Feature2","Add Feature", choices = NULL),
                                  textInput("vector_inventory_2_Cassette3Feature2Desc",""),
                                  selectInput("vector_inventory_2_Cassette3Feature3","Add Feature", choices = NULL),
                                  textInput("vector_inventory_2_Cassette3Feature3Desc",""),
                                  
                                  br(), hr(),
                                  h4("Cassette 8"),
                                  selectInput("vector_inventory_2_Cassette8Promoter","Promoter", choices = NULL),
                                  selectInput("vector_inventory_2_Cassette8Gene","Gene", choices =  NULL),
                                  selectInput("vector_inventory_2_Cassette8Teminator","Teminator", choices = NULL),
                                  selectInput("vector_inventory_2_Cassette8Feature1","Add Feature", choices = NULL),
                                  textInput("vector_inventory_2_Cassette8Feature1Desc",""),
                                  selectInput("vector_inventory_2_Cassette8Feature2","Add Feature", choices = NULL),
                                  textInput("vector_inventory_2_Cassette8Feature2Desc",""),
                                  selectInput("vector_inventory_2_Cassette8Feature3","Add Feature", choices = NULL),
                                  textInput("vector_inventory_2_Cassette8Feature3Desc",""),
                                  ),
                           column(2, h4("Cassette 4"),
                                  selectInput("vector_inventory_2_Cassette4Promoter","Promoter", choices = NULL),
                                  selectInput("vector_inventory_2_Cassette4Gene","Gene", choices =  NULL),
                                  selectInput("vector_inventory_2_Cassette4Teminator","Teminator", choices = NULL),
                                  selectInput("vector_inventory_2_Cassette4Feature1","Add Feature", choices = NULL),
                                  textInput("vector_inventory_2_Cassette4Feature1Desc",""),
                                  selectInput("vector_inventory_2_Cassette4Feature2","Add Feature", choices = NULL),
                                  textInput("vector_inventory_2_Cassette4Feature2Desc",""),
                                  selectInput("vector_inventory_2_Cassette4Feature3","Add Feature", choices = NULL),
                                  textInput("vector_inventory_2_Cassette4Feature3Desc",""),
                                  
                                  br(), hr(),
                                  h4("Cassette 9"),
                                  selectInput("vector_inventory_2_Cassette9Promoter","Promoter", choices = NULL),
                                  selectInput("vector_inventory_2_Cassette9Gene","Gene", choices =  NULL),
                                  selectInput("vector_inventory_2_Cassette9Teminator","Teminator", choices = NULL),
                                  selectInput("vector_inventory_2_Cassette9Feature1","Add Feature", choices = NULL),
                                  textInput("vector_inventory_2_Cassette9Feature1Desc",""),
                                  selectInput("vector_inventory_2_Cassette9Feature2","Add Feature", choices = NULL),
                                  textInput("vector_inventory_2_Cassette9Feature2Desc",""),
                                  selectInput("vector_inventory_2_Cassette9Feature3","Add Feature", choices = NULL),
                                  textInput("vector_inventory_2_Cassette9Feature3Desc","")
                                  ),
                           
                           column(2, h4("Cassette 5"),
                                  selectInput("vector_inventory_2_Cassette5Promoter","Promoter", choices = NULL),
                                  selectInput("vector_inventory_2_Cassette5Gene","Gene", choices =  NULL),
                                  selectInput("vector_inventory_2_Cassette5Teminator","Teminator", choices = NULL),
                                  selectInput("vector_inventory_2_Cassette5Feature1","Add Feature", choices = NULL),
                                  textInput("vector_inventory_2_Cassette5Feature1Desc",""),
                                  selectInput("vector_inventory_2_Cassette5Feature2","Add Feature", choices = NULL),
                                  textInput("vector_inventory_2_Cassette5Feature2Desc",""),
                                  selectInput("vector_inventory_2_Cassette5Feature3","Add Feature", choices = NULL),
                                  textInput("vector_inventory_2_Cassette5Feature3Desc",""),
                                  
                                  br(), hr(),
                                  h4("Cassette 10"),
                                  selectInput("vector_inventory_2_Cassette10Promoter","Promoter", choices = NULL),
                                  selectInput("vector_inventory_2_Cassette10Gene","Gene", choices =  NULL),
                                  selectInput("vector_inventory_2_Cassette10Teminator","Teminator", choices = NULL),
                                  selectInput("vector_inventory_2_Cassette10Feature1","Add Feature", choices = NULL),
                                  textInput("vector_inventory_2_Cassette10Feature1Desc",""),
                                  selectInput("vector_inventory_2_Cassette10Feature2","Add Feature", choices = NULL),
                                  textInput("vector_inventory_2_Cassette10Feature2Desc",""),
                                  selectInput("vector_inventory_2_Cassette10Feature3","Add Feature", choices = NULL),
                                  textInput("vector_inventory_2_Cassette10Feature3Desc","")
                                  )
                    )
                  )
                ))
      ),
      fluidRow(
        column(2, offset = 7, actionBttn("vector_inventory_2_Clear", "Clear", size = "xs", style = "jelly", color = "primary", block = T))
      ),hr(), br(),
    fluidRow(
      column(12,
             column(5),
             column(2, actionBttn("xvector_inventory_1_FormToPicture", "Form to Picture", size = "xs", style = "jelly", color = "primary", block = T)),
             column(1),
             column(2, actionBttn("xvector_inventory_1_ControlForm", "Control Form", size = "xs", style = "jelly", color = "primary", block = T)),
             column(1, actionBttn("xvector_inventory_1_Exit", "Exit", size = "xs", style = "jelly", color = "primary", block = T))
      )
    )
      
  )